`ifndef NEXYS_A7_UART_MATMUL_PARAMS_VH
`define NEXYS_A7_UART_MATMUL_PARAMS_VH

`define DEFAULT_MATRIX_N   8
`define DEFAULT_ARRAY_N    8
`define DEFAULT_DW         8
`define DEFAULT_ACCW      (2*`DEFAULT_DW + $clog2(`DEFAULT_MATRIX_N))

`define DEFAULT_CLK_HZ     100_000_000
`define DEFAULT_UART_BAUD  921600

`endif
